CREATE TABLE notifications (
	notification_id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id),
	type VARCHAR(50) NOT NULL,
	title VARCHAR(150) NOT NULL,
	message TEXT NOT NULL,
	is_read BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
