spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt.secret=MyVerySecretKeyForEcoTrackJWTAuthentication2026MyVerySecretKey
jwt.expiration=86400000