ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS total_xp INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS challenges
    ADD COLUMN IF NOT EXISTS xp INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS challenges
    ADD COLUMN IF NOT EXISTS difficulty VARCHAR(20) NOT NULL DEFAULT 'Easy';

ALTER TABLE IF EXISTS challenges
    ADD COLUMN IF NOT EXISTS badge_id VARCHAR(20);

ALTER TABLE IF EXISTS challenge_participants
    ADD COLUMN IF NOT EXISTS xp_awarded BOOLEAN NOT NULL DEFAULT FALSE;

